tap "felixkratz/formulae"
tap "homebrew/bundle"
tap "homebrew/services"
tap "nikitabobko/tap"
# Apjanke's fork of the classic cowsay project
brew "cowsay"
# Command-line DNS Client for Humans
brew "doggo"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Tool to convert a Wallpaper's color scheme / palette
brew "gowall"
# Mac App Store command-line interface
brew "mas"
# Manage multiple Node.js versions
brew "nvm"
# Command-line tool to view objects (JSON/YAML/TOML) in TUI tree widget
brew "otree"
# Terminal slideshow tool
brew "presenterm"
# Prints a steam locomotive if you type sl instead of ls
brew "sl"
# Cross-platform application to monitor your network traffic
brew "sniffnet"
# Modern and pretty fancy file manager for the terminal
brew "superfile"
# TUI to view and query tabular files (CSV,TSV, Parquet, etc.)
brew "tabiew"
# Simple terminal image viewer written in Rust
brew "viu"
# A window border system for macOS
brew "felixkratz/formulae/borders"
# AirPods companion app
cask "airbuddy"
# Menu bar tool to limit maximum charging percentage
cask "aldente"
# Enable Windows-like alt-tab
cask "alt-tab"
# Application uninstaller
cask "appcleaner"
# 3D model slicing software for 3D printers, maintained by Bambu Lab
cask "bambu-studio"
# Graphical configurator for Dygma Raise keyboards
cask "bazecor"
# Utility improving 3rd party mouse performance and functionalities
cask "bettermouse"
# OpenAI's official ChatGPT desktop app
cask "chatgpt"
# Anthropic's official Claude AI desktop app
cask "claude"
# Tool to remove unnecessary files and folders from disk
cask "cleanmymac"
# Screen capturing tool
cask "cleanshot"
# Server and cloud storage browser
cask "cyberduck"
# Virtual monitor for screen sharing
cask "deskpad"
# App to build and share containerised applications and microservices
cask "docker"
# Downloads videos from different websites
cask "downie"
# Productivity app
cask "dropzone"
# Desktop client for Ente Photos
cask "ente"
# Desktop client for Ente Auth
cask "ente-auth"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg-nerd-font"
cask "font-monaspace-nerd-font"
cask "font-roboto-mono-nerd-font"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Free and open-source image editor
cask "gimp"
# Keyboard shortcuts for every button on your screen
cask "homerow"
# Free and open-source media player
cask "iina"
# Menu bar manager
cask "jordanbaird-ice"
# Keyboard customiser
cask "karabiner-elements"
# Open-source keystroke visualiser
cask "keycastr"
# Custom Discord client
cask "legcord"
# Tool to control external monitor brightness & volume
cask "monitorcontrol"
# VPN client
cask "mullvadvpn"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Get up and running with large language models locally
cask "ollama"
# Verify system files structure, run miscellaneous maintenance and more
cask "onyx"
# WebKit based web browser
cask "orion"
# Client for Proton Drive
cask "proton-drive"
# Bridges Proton Mail to email clients supporting IMAP and SMTP protocols
cask "proton-mail-bridge"
# Desktop client for Proton Pass
cask "proton-pass"
# VPN client focusing on security
cask "protonvpn"
# Control your tools with a few keystrokes
cask "raycast"
# Open source virtual/remote desktop application
cask "rustdesk"
# Instant messaging application focusing on security
cask "signal"
# System monitor for the menu bar
cask "stats"
# Mesh VPN based on WireGuard
cask "tailscale"
# Customizable email client
cask "thunderbird"
# Web browser focusing on security
cask "tor-browser"
# Wine wrapper built with SwiftUI
cask "whisky"
# Multiplayer code editor
cask "zed"
# Gecko based web browser
cask "zen-browser"
