tap "felixkratz/formulae"
tap "homebrew/bundle"
tap "homebrew/services"
tap "nikitabobko/tap"
# Run your GitHub Actions locally
brew "act"
# Apjanke's fork of the classic cowsay project
brew "cowsay"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Mac App Store command-line interface
brew "mas"
# Command-line tool to view objects (JSON/YAML/TOML) in TUI tree widget
brew "otree"
# Prints a steam locomotive if you type sl instead of ls
brew "sl"
# TUI to view and query tabular files (CSV,TSV, Parquet, etc.)
brew "tabiew"
# A window border system for macOS
brew "felixkratz/formulae/borders"
# AeroSpace is an i3-like tiling window manager for macOS
cask "aerospace"
# AirPods companion app
cask "airbuddy"
# Menu bar tool to limit maximum charging percentage
cask "aldente"
# Enable Windows-like alt-tab
cask "alt-tab"
# Application uninstaller
cask "appcleaner"
# 3D model slicing software for 3D printers, maintained by Bambu Lab
cask "bambu-studio"
# Graphical configurator for Dygma Raise keyboards
cask "bazecor"
# Utility improving 3rd party mouse performance and functionalities
cask "bettermouse"
# OpenAI's official ChatGPT desktop app
cask "chatgpt"
# Screen capturing tool
cask "cleanshot"
# Server and cloud storage browser
cask "cyberduck"
# Virtual monitor for screen sharing
cask "deskpad"
# App to build and share containerised applications and microservices
cask "docker"
# Productivity app
cask "dropzone"
# Desktop client for Ente Photos
cask "ente"
# Desktop client for Ente Auth
cask "ente-auth"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg-nerd-font"
cask "font-monaspace-nerd-font"
cask "font-roboto-mono-nerd-font"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Keyboard shortcuts for every button on your screen
cask "homerow"
# Free and open-source media player
cask "iina"
# Menu bar manager
cask "jordanbaird-ice"
# Keyboard customiser
cask "karabiner-elements"
# Custom Discord client
cask "legcord"
# Discover, download, and run local LLMs
cask "lm-studio"
# Tool to control external monitor brightness & volume
cask "monitorcontrol"
# VPN client
cask "mullvadvpn"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Client for Proton Drive
cask "proton-drive"
# Client for Proton Mail and Proton Calendar
cask "proton-mail"
# Desktop client for Proton Pass
cask "proton-pass"
# VPN client focusing on security
cask "protonvpn"
# Control your tools with a few keystrokes
cask "raycast"
# Instant messaging application focusing on security
cask "signal"
# System monitor for the menu bar
cask "stats"
# Mesh VPN based on WireGuard
cask "tailscale"
# Web browser focusing on security
cask "tor-browser"
# Multiplayer code editor
cask "zed"
# Gecko based web browser
cask "zen-browser"
mas "ExcalidrawZ", id: 6636493997
mas "Final Cut Pro", id: 424389933
mas "Infuse", id: 1136220934
mas "Keka", id: 470158793
mas "Xcode", id: 497799835
