matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .github/workflows/extra-config/.wordlist.txt 
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: true
  sources:
  - '**/*.md'
  default_encoding: utf-8
